### PR TITLE
Fix the build issue in mcl repo

### PR DESCRIPTION
**Pull request by robin-thomas**

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Build is complaining about m4 in the $PATH

**Comment by robin-thomas** [comment]
@prestonvanloon The configure script from GMP requires m4 in the PATH. I have a minimum BUILD file to get everything. But it still requires m4.

**Comment by prestonvanloon** [comment]
Done, but it’s still failing 
https://buildkite.com/prysmatic-labs/mcl/builds/67#7ea0552c-1c59-4c3b-80f8-36eafb00fbe4

**Comment by robin-thomas** [comment]
@prestonvanloon Because the configure script from GMP requires m4 in the PATH. I have added a minimum external BUILD file to build everything. But it still requires m4.

**Comment by prestonvanloon** [comment]
Can we use this? 
https://github.com/jmillikin/rules_m4

**Comment by robin-thomas** [comment]
Let me remove the m4 from my system, and try using that bazel m4 rule.

**Comment by prestonvanloon** [comment]
Thanks! I appreciate all of your efforts, especially on Christmas Eve

**Comment by robin-thomas** [comment]
I'm getting the below error (transitive workspace issue of Bazel is really a mess).
```bazel-out/host/bin/external/m4_v1.4.18/_objs/m4_lib/error.o:error.c:function error: error: undefined reference to 'getprogname'
bazel-out/host/bin/external/m4_v1.4.18/_objs/m4_lib/error.o:error.c:function error_at_line: error: undefined reference to 'getprogname'
```
which should be part of libc: https://www.freebsd.org/cgi/man.cgi?query=getprogname&sektion=3

Actually, I'm based in Singapore. So it's already Xmas here

**Comment by prestonvanloon** [comment]
Can you push your latest code? It looked like the rules_m4 repo provided a macro to install its transitive deps

**Comment by robin-thomas** [comment]
Yes. It provides a macro, which was what I was using.

But m4 alone is not enough. Because I used the system m4 to process the same file. There are some definitions that are not processed (which are initialized by configure script)

**Comment by prestonvanloon** [comment]
I see. I’ll have to take a further look tomorrow.

The goal would be that users don’t need to install m4 or other system dependencies, but this seems to be much more involved than anticipated

**Comment by robin-thomas** [comment]
m4 comes pre-installed in most systems anyway. But this wont be an easy task. I'll also try solving it.

**Comment by prestonvanloon** [comment]
Sounds good. I’ll add it to the build agent if you can’t find a trivial solution

**Comment by robin-thomas** [comment]
I somehow got the m4 binary generated. I just need to get Bazel that path, but with Bazel and their sandboxes, seems a bit tough to solve. So I'm looking into that now.

**Comment by robin-thomas** [comment]
@prestonvanloon Somehow fixed all this m4 issue. Seems like this was too much work than what I had initially thought

**Comment by robin-thomas** [comment]
Can you kindly review it?

**Review by prestonvanloon — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Nice job

**Pull request merged**
